spring:
  datasource:
    plataform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL 
    hibernate:
      ddl-auto: update
